### ISSUE TITLE
0.1.2-alpha6 subscription does not receive events

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-csharp#20]
When testing [Release 0.1.2-alpha6](http://www.nuget.org/packages/RingCentralSDK/0.1.2-alpha6) on NuGet, the subscription is created but no event messages are received. [Release 0.1.1](http://www.nuget.org/packages/RingCentralSDK/0.1.1) behaves as expected using the same code. 

To reproduce:

1. Configure a RC account where the `username` phone number can receive calls and texts
2. Run the following code with 0.1.2-alpha6 and 0.1.1
3. Call or send a SMS text to the `username` phone number 
4. Observe the console. 0.1.1 will display events for inbound calls and texts. 0.1.2-alpha6 will not display such events.

```csharp
using System;

using RingCentral;
using RingCentral.Subscription;

namespace consoletest
{
	class MainClass
	{
		public static void Action(object message) {
			Console.WriteLine (message.ToString ());
		}

		public static void Main (string[] args)
		{
			var appKey = "myAppKey";
			var appSecret = "myAppSecret";
			var serverUrl = "https://platform.devtest.ringcentral.com";
			var username = "12223334444";
			var extension = "101";
			var password = "myPassword";

			var sdk = new RingCentral.SDK.SDK(appKey, appSecret, serverUrl, "appName", "appVersion");
			sdk.GetPlatform().Authorize(username, extension, password, true);

			var subscription = new RingCentral.Subscription.SubscriptionServiceImplementation(){ _platform = sdk.GetPlatform()};
			subscription.AddEvent("/restapi/v1.0/account/~/extension/~/presence");
			subscription.AddEvent("/restapi/v1.0/account/~/extension/~/message-store");
			var response = subscription.Subscribe(Action,Action,Action);

			var wait = Console.ReadLine ();

			Console.WriteLine ("DONE!");
		}
	}
}
```

Upon receiving a text, the code above should write something like the following the console. This occurs with 0.1.1 but not 0.1.2-alpha6.

```json
{"uuid":"11112222-3333-4444-5555-666677778888","event":"/restapi/v1.0/account/~/extension/11111111/message-store","timestamp":"2016-04-03T04:18:11.443Z","subscriptionId":"21112222-3333-4444-5555-666677778888","body":{"extensionId":22222222,"lastUpdated":"2016-04-03T04:18:05.351+0000","changes":[{"type":"SMS","newCount":1,"updatedCount":0}]}}
```

**Comment by nrobison** [comment]
This is an issue dealing with decryption of the messages. The issue is the encryption key is sent as a Base64 encoded string. PubNub will automatically decrypt messages if provided with a valid key. Without knowledge of how the encryption key is sent, I cannot convert it to a string to be used by PubNub. PubNub will only accept a string and not a byte[]. Using other packages available we are able to achieve the decoding of the message. 

Please update to the latest pre-release package to confirm this is fixed for you.

**Comment by grokify** [comment]
@nrobison Thanks fro the update. I tried alpha7 and everything looks good.

**Comment by grokify** [comment]
For a follow up, on April 7, I only tested Xamarin.Mac. Today I tested `0.1.21` on Xamarin.Android and Xamarin.iOS. It appears this issue has been resolved for Xamarin.Mac and Xamarin.Android but Xamarin.iOS is still not receiving events.
